name: 'tests'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: 'Checkout Project'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: 'actions/setup-node@v2.1.3'
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Cache dependencies'
        uses: 'actions/cache@v2'
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: 'Install Dependencies'
        run: 'npm install'

      - name: 'Run Tests'
        run: 'npm test'
